version: '2'
services:
  ui:
    build: ./nawyfe
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    build: ./Node-mongo
    ports:
      - '7070:8000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
